# -*- coding: utf-8 -*-
"""quant (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qAPhI4SuduyUS66eZaS_vsAQOJ3lBAU
"""

!pip install pandas pyarrow

!pip install pyarrow
!pip install fastparquet

import pandas as pd

# Read the Parquet file
df = pd.read_parquet('/content/47100CE.parquet')

print(df.head())

import pandas as pd

# Load the Parquet file
file_name = '47100CE.parquet'
df = pd.read_parquet(file_name)

print(df.columns)

import pandas as pd



# Convert 'date' column to datetime
df['date'] = pd.to_datetime(df['date'])

# Filter data for 10th January 2024
df_10th_jan = df[df['date'].dt.date == pd.to_datetime('2024-01-10').date()]


df_10th_jan.set_index('date', inplace=True)

print("✅ Data filtered for 10th January 2024")
print(df_10th_jan.head())

# Resample into 5-minute intervals for OHLC and sum volume
ohlc_5min = df_10th_jan.resample('5T').agg({
    'open': 'first',
    'high': 'max',
    'low': 'min',
    'close': 'last',
    'volume': 'sum'
})

# Drop rows with NaN values (empty intervals)
ohlc_5min.dropna(inplace=True)

print("✅ 5-minute candles generated")
print(ohlc_5min.head())

import os

# Reset index to turn 'date' back into a column
ohlc_5min.reset_index(inplace=True)

os.makedirs('5min_candles', exist_ok=True)

# Save to CSV
ohlc_5min.to_csv('5min_candles/47100CE_5min_candles.csv', index=False)

print("✅ CSV saved as '5min_candles/47100CE_5min_candles.csv'")

# Extract High, Low, and Close for the entire day
daily_high = df_10th_jan['high'].max()
daily_low = df_10th_jan['low'].min()
daily_close = df_10th_jan['close'].iloc[-1]  # Last close of the day

# Pivot Point (P)
pivot_point = (daily_high + daily_low + daily_close) / 3

# Resistance Levels
R1 = pivot_point + 0.382 * (daily_high - daily_low)
R2 = pivot_point + 0.618 * (daily_high - daily_low)
R3 = pivot_point + (daily_high - daily_low)

# Support Levels
S1 = pivot_point - 0.382 * (daily_high - daily_low)
S2 = pivot_point - 0.618 * (daily_high - daily_low)
S3 = pivot_point - (daily_high - daily_low)

# Display the Fibonacci Pivot Points
print("📊 Fibonacci Pivot Points for 10th Jan 2024")
print(f"Pivot Point (P): {pivot_point:.2f}")
print(f"Resistance 1 (R1): {R1:.2f}")
print(f"Resistance 2 (R2): {R2:.2f}")
print(f"Resistance 3 (R3): {R3:.2f}")
print(f"Support 1 (S1): {S1:.2f}")
print(f"Support 2 (S2): {S2:.2f}")
print(f"Support 3 (S3): {S3:.2f}")

!git --version  # Check if git is installed
!sudo apt-get install git  # Install git if not available

# Set your GitHub username and email
!git config --global user.name "prathamshirol"
!git config --global user.email "prathamshirol53@gmail.com"

# Replace 'YourGitHubUsername' and 'RepoName' with your details
!git clone https://github.com/prathamshirol/quant.git

import shutil

# Move the correct CSV file to your repo
shutil.move('/content/5min_candles/47100CE_5min_candles.csv', '/content/quant')

